import { Inter } from "next/font/google";
import "./globals.css";
import Navber from "@/Component/Navber";
import Footer from "@/Component/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "next-project2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col justify-center">
          <Navber></Navber>
          {children}
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
